### ISSUE TITLE
Join forces

### ISSUE THREAD

**Issue by bm-stschneider** [Fooxly/workspace#1]
Wouldn't it make sense to work together maybe? Peter Schmalfeldt has a way better UI for administer hidden files and folders and also supports patterns for hiding stuff, but he seems to have no time to fix bugs with showing/hiding individual patterns in the tree view.

https://marketplace.visualstudio.com/items?itemName=RedVanWorkshop.explorer-exclude-vscode-extension

**Comment by thomGNL** [comment]
Hello, we are currently looking into reversing the process that you can focus folders and files instead of hide them. This will make it possible for developer to create a custom workspace in which you can only view your src files (instead of for example your iOS and Android folder, node modules etc.) But we are currently a bit limited to the files.exclude glob functionality. But we are looking for another way around that to get the functionality we would like.

So thats why we are currently not joining forces, we have another vision for this package than what the explorer exclude is (which in itself is an amazing package). Maybe we will look into helping them with their package in the future.

**Comment by gimbo** [comment]
I guess nothing came of that hope, given that this extension is still just another manager for `files.exclude` with essentially similar capabilities to Explorer Exclude, AFAICS...?

**Comment by LucHermkens** [comment]
Due to the time it takes to work on our commercial products and solutions, we cannot extend the functionality of this extension right now. But feel free to do it yourself and create a pull request so we can merge it! 😄 We believe that this extension really helps us to be more productive in our day-to-day work, and we hope it will do the same for you and the other nearly 7000 users that have it installed. If you think otherwise, just don't use it.

While Explorer Exclude works great, it hasn't been updated for over 2 years, which comes with security vulnerabilities and maybe other issues (aside from the open ones) in the future. Our extension also uses less resources and is well documented, which is why we prefer it over the alternatives.

> The Fooxly Team
